### PR TITLE
fix sed invocation on osx

### PR DESCRIPTION
**Pull request by aep**

### CODE REVIEW

**Comment by daveshah1** [comment]
Please can you briefly explain the problem that this is fixing?

**Comment by aep** [comment]
sed on osx doesnt accept GNU commandline behaviour.


```
[2] aep@wurstbox: ~/kram/icestorm/icebox sudo make install
Password:
mkdir -p /usr/local/share/icebox
mkdir -p /usr/local/bin
cp chipdb-384.txt    /usr/local/share/icebox/
cp chipdb-1k.txt     /usr/local/share/icebox/
cp chipdb-8k.txt     /usr/local/share/icebox/
cp chipdb-5k.txt     /usr/local/share/icebox/
cp chipdb-u4k.txt    /usr/local/share/icebox/
cp chipdb-lm4k.txt   /usr/local/share/icebox/
cp icebox.py         /usr/local/bin/icebox.py
cp iceboxdb.py       /usr/local/bin/iceboxdb.py
cp icebox_chipdb.py  /usr/local/bin/icebox_chipdb
cp icebox_diff.py    /usr/local/bin/icebox_diff
cp icebox_explain.py /usr/local/bin/icebox_explain
cp icebox_asc2hlc.py /usr/local/bin/icebox_asc2hlc
cp icebox_hlc2asc.py /usr/local/bin/icebox_hlc2asc
cp icebox_colbuf.py  /usr/local/bin/icebox_colbuf
cp icebox_html.py    /usr/local/bin/icebox_html
cp icebox_maps.py    /usr/local/bin/icebox_maps
cp icebox_vlog.py    /usr/local/bin/icebox_vlog
cp icebox_stat.py    /usr/local/bin/icebox_stat
sed -i 's+import iceboxdb+import iceboxdb as iceboxdb+g' /usr/local/bin/icebox.py
sed: 1: "/usr/local/bin/icebox.py": extra characters at the end of l command
make: *** [install] Error 1

```

**Comment by saferif** [comment]
I am experiencing the same problem, and can confirm that this patch fixes it. I don't know if it still works on Linux, though.

**Comment by defcon8** [comment]
> and can confirm that this patch fixes it.

What patch? Where?

**Comment by aep** [comment]
you're commenting on it.

see here how to apply

https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

**Comment by mmicko** [comment]
Issue addressed in https://github.com/YosysHQ/icestorm/commit/9fe28369aaf1f98090b9ecfded6ef22599cc09d0

**Pull request closed without merging**
